[package]
name = "MoveUp"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
windows = { version = "0.61.3", features = ["Win32_Storage_FileSystem"] }
winapi = { version = "0.3.9", features = ["wincon"] }

[build-dependencies]
winresource = "0.1.22"
